### ISSUE TITLE
Problems with some links in the README for gallery examples

### ISSUE THREAD

**Issue by jibarnum** [heliophysicsPy/gallery#14]
While figuring out how to contribute an example to the gallery, I clicked on the links in the following sentences (pulled from README's 'Contributing' paragraph) and was told "this page does not exist yet".

"You can see an example gallery here." 
"For the required syntax see the sphinx gallery syntax documentation."

**Comment by Cadair** [comment]
It looks like the sphinx gallery docs have moved. 

New URL is https://sphinx-gallery.github.io/

**Comment by sapols** [comment]
So the new links will be:

https://sphinx-gallery.github.io/stable/auto_examples/index.html
https://sphinx-gallery.github.io/stable/syntax.html

Respectively.

**Comment by sapols** [comment]
Updated.
