### ISSUE TITLE
Top-level gallery page (Examples tab from PyHC's home page) doesn't have link back to the home page.

### ISSUE THREAD

**Issue by jibarnum** [heliophysicsPy/gallery#20]
All the other tabs on the PyHC website retain the bar at the top of the page that links to other tabs/the home page.

**Comment by Cadair** [comment]
We solved this problem in SunPy by building both the gallery (and documentation pages) and the main website using sphinx. It meant we have a consistent style over all the sites because they all use the same tech and sphinx theme.

**Comment by ehsteve** [comment]
Let’s not do that here please. I do love the SunPy webpage but not Sphinx! ;)

**Comment by Cadair** [comment]
Sphinx is great. Better than Jekyll.

On 25 September 2019 12:32:09 BST, Steven Christe <notifications@github.com> wrote:
>Let’s not do that here please. I do love the SunPy webpage but not
>Sphinx! ;)>
>>
>-- >
>You are receiving this because you commented.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/heliophysicsPy/gallery/issues/20#issuecomment-534979042

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
